[workspace]

members = [ "cargo_play", "closure_iter", "collection_proj", "common_concept", "enum_proj", "error_handling", "generic_proj", "guess_this","intro", "minigrep", "module_sys", "ownership", "smart_ptr", "struct_proj", "test_proj"]
