[package]
name = "number_regn"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.0.34", default-features = false }
ndarray = { version = "0.16.1", default-features = false }
rand = "0.8.5"
rand_distr = "0.4.3"
